cli_config_file_name: embeddings/cli.yml
i18n_file_name: embeddings/i18n.yml
template_file_names:
  main_template: templates/main.go.tmpl
  init_template: templates/init.go.tmpl
  init_handlers_template: templates/handlers.init.go.tmpl
  init_injectors_template: templates/injectors.init.go.tmpl
  new_handler_template: templates/handlers.new.go.tmpl
  new_injector_template: templates/injectors.new.go.tmpl
output_files:
  main_file: main.go
  init_file: init.go
  init_handlers_file: handlers/init.gen.go
  init_injectors_file: injectors/init.gen.go
  new_handler_file: handlers/${handler_name}.go
  new_injector_file: injectors/${injector_name}.go